port: 9090
verbose: true

clusters:
  - name: trino
    type: trino
    url: http://trino:8080
    catalog: tpch
    schema: sf1
    sourceListScan: disable
    timeout: 120000

dataCubes:
  - name: orders
    clusterName: trino
    source: orders
    title: TPC-H Orders
    description: Orders from the TPC-H benchmark dataset (1992-1998)
    timeAttribute: orderdate
    introspection: no-autofill
    refreshRule:
      rule: fixed
      time: PT1M
    attributeOverrides:
      - name: orderkey
        type: NUMBER
      - name: custkey
        type: NUMBER
      - name: orderstatus
        type: STRING
      - name: totalprice
        type: NUMBER
      - name: orderdate
        type: TIME
      - name: orderpriority
        type: STRING
      - name: clerk
        type: STRING
      - name: shippriority
        type: NUMBER
      - name: comment
        type: STRING
    dimensions:
      - name: orderdate
        kind: time
        formula: $orderdate
        title: Order Date
      - name: orderstatus
        formula: $orderstatus
        title: Order Status
      - name: orderpriority
        formula: $orderpriority
        title: Order Priority
      - name: clerk
        formula: $clerk
        title: Clerk
    measures:
      - name: count
        formula: $main.count()
        title: Order Count
      - name: total_price
        formula: $main.sum($totalprice)
        title: Total Price
      - name: avg_price
        formula: $main.average($totalprice)
        title: Average Price
